import { validateConfig, type MonitorConfig, type MonitorEnvelope } from "./types.js";
import type { AckRecoveryService } from "./ack_recovery.js";
import type { PageAckService } from "./page_ack.js";
import type { MonitorScheduler } from "./scheduler.js";
export interface ApiEvent { version?:string; rawPath?:string; requestContext?:{http?:{method?:string}}; body?:string|null; headers?:Record<string,string|undefined> }
export interface ApiResponse { statusCode:number; headers?:Record<string,string>; body:string }
export interface RuntimeDependencies { config:MonitorConfig; ingest:{ingest(envelope:unknown):Promise<{kind:"ACK";body:unknown}|{kind:"RECOVERY_REQUIRED";commit:unknown}|{kind:"RETRY"|"QUARANTINED"|"REJECTED"|"UNKNOWN";reason:string}>}; recovery:Pick<AckRecoveryService,"recover">; pageAck:Pick<PageAckService,"acknowledge">; scheduler:Pick<MonitorScheduler,"run">; clock:{now():Promise<{timeMs:number}>} }
function json(statusCode:number,value:unknown,headers:Record<string,string>={}):ApiResponse{return {statusCode,headers:{"content-type":"application/json",...headers},body:JSON.stringify(value)}}
function parseBody(event:ApiEvent):unknown {if(typeof event.body!=="string")throw new Error("body required");return JSON.parse(event.body)}
function authorization(headers:Record<string,string|undefined>):string {return headers.authorization??headers.Authorization??""}
function path(event:ApiEvent):string {return event.rawPath??""}
function mapError(error:unknown):ApiResponse {const name=error instanceof Error?error.name:"";if(name.includes("Authorization")||name.includes("principal"))return json(401,{error:"UNAUTHORIZED"});if(name.includes("Conflict"))return json(409,{error:"CONFLICT"});if(name.includes("Validation")||name.includes("Integrity"))return json(400,{error:"REJECTED"});return json(503,{error:"UNKNOWN"},{"retry-after":"1"})}
function ingestResponse(result:Awaited<ReturnType<RuntimeDependencies["ingest"]["ingest"]>>):ApiResponse {if(result.kind==="ACK")return json(200,result.body);if(result.kind==="QUARANTINED")return json(409,{error:result.kind,reason:result.reason});if(result.kind==="REJECTED")return json(400,{error:result.kind,reason:result.reason});if(result.kind==="RECOVERY_REQUIRED")return json(409,{error:result.kind,commit:result.commit});return json(503,{error:result.kind,reason:result.reason},{"retry-after":"1"})}
export function createHandler(deps:RuntimeDependencies){if(!deps||!deps.config)throw new TypeError("runtime dependencies are required");return async(event:ApiEvent & {kind?:unknown;source?:unknown;scheduledFor?:unknown}):Promise<ApiResponse>=>{try{if(event.kind!==undefined){if(event.kind!=="monitor_tick"||event.source!=="aws-scheduler"||Object.keys(event).some(k=>!["kind","source","scheduledFor"].includes(k)))return json(400,{error:"REJECTED"});const now=(await deps.clock.now()).timeMs;return json(200,await deps.scheduler.run(typeof event.scheduledFor==="number"?event.scheduledFor:now));}const method=event.requestContext?.http?.method??"";const p=path(event);if(method!=="POST")return json(404,{error:"NOT_FOUND"});if(p==="/v1/ingest")return ingestResponse(await deps.ingest.ingest(parseBody(event)));if(p==="/v1/ack/recovery")return json(200,await deps.recovery.recover(parseBody(event) as any));const m=/^\/v1\/incidents\/([^/]+)\/pages\/([^/]+)\/ack$/.exec(p);if(m){const body=parseBody(event) as any;return json(200,await deps.pageAck.acknowledge({...body,incident_id:body.incident_id??m[1],page_id:body.page_id??m[2]},{authorization:authorization(event.headers??{}),method,path:p}))}return json(404,{error:"NOT_FOUND"})}catch(error){return mapError(error)}}}
export async function handler(event:ApiEvent):Promise<ApiResponse>{throw new Error("runtime is not initialized: MONITOR_CONFIG_JSON and concrete AWS bindings are required")}
export function loadConfig(raw=process.env.MONITOR_CONFIG_JSON):MonitorConfig {if(!raw)throw new Error("MONITOR_CONFIG_JSON is required");let parsed:unknown;try{parsed=JSON.parse(raw)}catch{throw new Error("MONITOR_CONFIG_JSON is invalid JSON")}return validateConfig(parsed)}
