import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import type { PublicSigningIdentity } from "./acks.js";

export class ValidationError extends Error { constructor(message: string) { super(message); this.name = "ValidationError"; } }
export interface LifecyclePayload { source_id:string; monotonic_seq:number; transition_id:string; state:"unknown"|"healthy"|"failed"; transition_at:number; source_version:string; sampled_at:number; nonce:string }
export interface MonitorEnvelope { kind:"canary-tick"|"CANARY_CONFIG_INVALID"|"canary-lifecycle"|"ATTEMPT_RESERVED"|"BREAKER_OPEN"|"BREAKER_CLOSED"; source:string; service:string; application:string; event_id:string; producer_seq:number; occurred_at:number; scheduled_for:number; version:"1"; key_id:string; credential_epoch:string; payload_digest:string; monitor_rearm_tuple_digest:string; payload?:LifecyclePayload; signature:string }
export interface SourceRegistration { source:string; service:string; application:string; keyId:string; credentialEpoch:string; secretArn:string; allowedKinds:string[]; intervalMs:number; sourceVersion:string; authoritySourceId:string|null; enabled:boolean }
export interface SourceCursor { source:string; service:string; application:string; keyId:string; credentialEpoch:string; lastSequence:number; lastEnvelopeDigest:string; lastOccurredAt:number; lastScheduledFor:number; firstAcceptedAt:number; lastAcceptedAt:number; expectedAt:number|null; quarantined:boolean; lifecycle: [string,number,string,"unknown"|"healthy"|"failed",number,string]|null; lastLifecycleNonce:string|null; sourceHealth:"healthy"|"failed"|"unknown"; sourceReason:string }
export interface MonitorConfig { version:"1"; region:string; monitorAccountId:string; sensitivityAccountId:string; verifierAccountId:string; monitorRearmTupleDigest:string; stateTable:string; stateNamespace:string; journalBucket:string; journalPrefix:string; journalRetentionMs:number; destination:string; snsTopicArn:string; sources:SourceRegistration[]; signerIdentities:PublicSigningIdentity[]; trustedTime:{endpoint:string;rootPem:string;intermediatePem:string;crlUrls:string[];minimumTimeMs:number;maxAdvanceMs:number;timeoutMs:number;maxResponseBytes:number;opensslPath:string}; witnessFunctionArn:string; maxPendingDeliveriesPerSource:100; onCallScheduleDigest:string }
const DIGEST=/^[0-9a-f]{64}$/; const HEX=/^[0-9a-f]+$/; const ID=/^[\u0021-\u007e]{1,256}$/;
const envelopeKeys=["kind","source","service","application","event_id","producer_seq","occurred_at","scheduled_for","version","key_id","credential_epoch","payload_digest","monitor_rearm_tuple_digest","signature"];
const lifecycleKeys=[...envelopeKeys.slice(0,-1),"payload","signature"];
const lifecycleKinds=new Set(["canary-lifecycle","ATTEMPT_RESERVED","BREAKER_OPEN","BREAKER_CLOSED"]);
const text=(v:unknown):v is string=>typeof v==="string"&&ID.test(v)&&v.trim()===v;
const positive=(v:unknown):v is number=>typeof v==="number"&&Number.isSafeInteger(v)&&v>0;
const nonnegative=(v:unknown):v is number=>typeof v==="number"&&Number.isSafeInteger(v)&&v>=0;
const plain=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
function exact(v:Record<string,unknown>, keys:string[]):boolean { const own=Object.keys(v); return own.length===keys.length&&keys.every(k=>Object.prototype.hasOwnProperty.call(v,k)); }
export function canonicalJson(value:unknown):string { const seen=new WeakSet<object>(); const walk=(v:unknown):unknown=>{ if(v===null||typeof v==="string"||typeof v==="boolean")return v; if(typeof v==="number"){if(!Number.isFinite(v)||!Number.isSafeInteger(v))throw new ValidationError("invalid JSON number");return v} if(typeof v!=="object"||seen.has(v as object))throw new ValidationError("non-canonical JSON value"); if(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype)throw new ValidationError("non-plain JSON object"); seen.add(v as object); if(Array.isArray(v))return v.map(walk); const o=v as Record<string,unknown>; return Object.keys(o).sort().reduce<Record<string,unknown>>((r,k)=>{r[k]=walk(o[k]);return r},{}); }; return JSON.stringify(walk(value)); }
export function sha256(value:string|Uint8Array):string { return createHash("sha256").update(value).digest("hex"); }
function lifecycle(value:unknown):value is LifecyclePayload { return plain(value)&&exact(value,["source_id","monotonic_seq","transition_id","state","transition_at","source_version","sampled_at","nonce"])&&text(value.source_id)&&positive(value.monotonic_seq)&&text(value.transition_id)&&["unknown","healthy","failed"].includes(String(value.state))&&nonnegative(value.transition_at)&&text(value.source_version)&&nonnegative(value.sampled_at)&&text(value.nonce); }
function fieldsValid(v:Record<string,unknown>):boolean { return text(v.source)&&text(v.service)&&text(v.application)&&text(v.event_id)&&positive(v.producer_seq)&&nonnegative(v.occurred_at)&&nonnegative(v.scheduled_for)&&v.version==="1"&&text(v.key_id)&&text(v.credential_epoch)&&DIGEST.test(String(v.payload_digest))&&DIGEST.test(String(v.monitor_rearm_tuple_digest))&&typeof v.signature==="string"&&HEX.test(v.signature)&&v.signature.length%2===0; }
export function parseEnvelope(input:unknown):MonitorEnvelope { if(!plain(input))throw new ValidationError("envelope must be object"); const v=input; const isLife=lifecycleKinds.has(String(v.kind)); if(!exact(v,isLife?lifecycleKeys:envelopeKeys)||!fieldsValid(v)||!((v.kind==="canary-tick"||v.kind==="CANARY_CONFIG_INVALID")?true:isLife)|| (isLife&&!lifecycle(v.payload)))throw new ValidationError("invalid envelope"); const digest=isLife?sha256(canonicalJson(v.payload)):sha256(JSON.stringify([v.kind,v.producer_seq,v.occurred_at,v.scheduled_for,v.version])); if(v.payload_digest!==digest)throw new ValidationError("payload digest mismatch"); return v as unknown as MonitorEnvelope; }
export function laneKey(registration:SourceRegistration):string { return sha256(JSON.stringify([registration.source,registration.service,registration.application])); }
export function authenticateEnvelope(envelope:MonitorEnvelope, registration:SourceRegistration, secret:Uint8Array):boolean { try { if(!registration.enabled||envelope.source!==registration.source||envelope.service!==registration.service||envelope.application!==registration.application||envelope.key_id!==registration.keyId||envelope.credential_epoch!==registration.credentialEpoch||!registration.allowedKinds.includes(envelope.kind)||secret.byteLength<32) return false; const payload=[envelope.kind,envelope.source,envelope.service,envelope.application,envelope.event_id,envelope.producer_seq,envelope.occurred_at,envelope.scheduled_for,envelope.version,envelope.key_id,envelope.credential_epoch,envelope.payload_digest,envelope.monitor_rearm_tuple_digest]; if(envelope.payload)payload.push(canonicalJson(envelope.payload)); const expected=createHmac("sha256",secret).update(JSON.stringify(payload)).digest("hex"); const a=Buffer.from(envelope.signature,"hex"),b=Buffer.from(expected,"hex"); return a.length===b.length&&timingSafeEqual(a,b); } catch{return false;} }
function account(arn:string):string|null { const m=/^arn:aws:iam::(\d{12}):role\/[A-Za-z0-9+=,.@_-]{1,512}$/.exec(arn); return m?.[1]??null; }
function arnAccount(arn:string):string|null { const m=/^arn:aws:[^:]+:[^:]*:(\d{12}):/.exec(arn); return m?.[1]??null; }
export function validateConfig(input:unknown):MonitorConfig { if(!plain(input))throw new ValidationError("config must be object"); const v=input; const keys=["version","region","monitorAccountId","sensitivityAccountId","verifierAccountId","monitorRearmTupleDigest","stateTable","stateNamespace","journalBucket","journalPrefix","journalRetentionMs","destination","snsTopicArn","sources","signerIdentities","trustedTime","witnessFunctionArn","maxPendingDeliveriesPerSource","onCallScheduleDigest"]; if(!exact(v,keys)||v.version!=="1"||![v.monitorAccountId,v.sensitivityAccountId,v.verifierAccountId].every(x=>/^\d{12}$/.test(String(x)))||new Set([v.monitorAccountId,v.sensitivityAccountId,v.verifierAccountId]).size!==3||!text(v.region)||!DIGEST.test(String(v.monitorRearmTupleDigest))||!text(v.stateTable)||!text(v.stateNamespace)||!text(v.journalBucket)||typeof v.journalPrefix!=="string"||!positive(v.journalRetentionMs)||!text(v.destination)||!/^arn:aws:sns:[^:]+:\d{12}:[A-Za-z0-9_-]+$/.test(String(v.snsTopicArn))||v.maxPendingDeliveriesPerSource!==100||!DIGEST.test(String(v.onCallScheduleDigest))||!Array.isArray(v.sources)||!Array.isArray(v.signerIdentities)||!plain(v.trustedTime))throw new ValidationError("invalid config"); const scopes=new Set<string>(),keysSeen=new Set<string>(); for(const s of v.sources){if(!plain(s)||!text(s.source)||!text(s.service)||!text(s.application)||!text(s.keyId)||!text(s.credentialEpoch)||!/^arn:aws:secretsmanager:[^:]+:\d{12}:secret[:/.].+/.test(String(s.secretArn))||!Array.isArray(s.allowedKinds)||s.allowedKinds.length===0||s.allowedKinds.some((k)=>!text(k))||![300000,60000].includes(s.intervalMs as number)||!text(s.sourceVersion)||!(s.authoritySourceId===null||text(s.authoritySourceId))||typeof s.enabled!=="boolean")throw new ValidationError("invalid source"); const scope=[s.source,s.service,s.application].join("\0"); if(scopes.has(scope)||keysSeen.has(s.keyId))throw new ValidationError("duplicate source scope or key"); scopes.add(scope);keysSeen.add(s.keyId); if(s.intervalMs===60000&&(s.authoritySourceId===null||!s.allowedKinds.some(k=>lifecycleKinds.has(k))))throw new ValidationError("invalid lifecycle source"); }
 const signerKeys=new Set<string>(); const signerRoles=new Set(["ingest-ack","recovery","manifest","page-ack","journal","witness"]); for(const i of v.signerIdentities){if(!plain(i)||!text(i.keyId)||!text(i.epoch)||!text(i.keyArn)||!text(i.publicKeySpkiPem)||typeof i.role!=="string"||!signerRoles.has(i.role)||signerKeys.has(`${i.keyId}\0${i.epoch}`)||!account(i.keyArn)||account(i.keyArn)!==(i.role==="witness"?v.verifierAccountId:v.monitorAccountId))throw new ValidationError("invalid signer identity");signerKeys.add(`${i.keyId}\0${i.epoch}`);}
 const t=v.trustedTime as Record<string,unknown>; if(t.endpoint!=="http://timestamp.digicert.com"||!text(t.rootPem)||!text(t.intermediatePem)||!Array.isArray(t.crlUrls)||t.crlUrls.some(x=>!text(x))||!positive(t.minimumTimeMs)||!nonnegative(t.maxAdvanceMs)||!positive(t.timeoutMs)||!positive(t.maxResponseBytes)||!text(t.opensslPath)||!/^arn:aws:lambda:[^:]+:\d{12}:function:[A-Za-z0-9_-]+:\d+$/.test(String(v.witnessFunctionArn))||arnAccount(String(v.witnessFunctionArn))!==v.verifierAccountId)throw new ValidationError("invalid trusted time"); return v as unknown as MonitorConfig; }
