import { createHmac } from "node:crypto";
import { describe, expect, it } from "vitest";
import { authenticateEnvelope, canonicalJson, parseEnvelope, parseSourceCursor, sha256, type LifecyclePayload, type MonitorEnvelope, type SourceRegistration } from "../src/types.js";
const secret = new TextEncoder().encode("s".repeat(32));
const registration: SourceRegistration = { source:"src", service:"svc", application:"app", keyId:"key", credentialEpoch:"1", secretArn:"arn:aws:secretsmanager:us-east-1:111111111111:secret:x", allowedKinds:["canary-tick","canary-lifecycle"], intervalMs:300000, sourceVersion:"v1", authoritySourceId:null, enabled:true };
function envelope(life=false): MonitorEnvelope { const p:LifecyclePayload={source_id:"src",monotonic_seq:1,transition_id:"tr",state:"healthy",transition_at:1000,source_version:"v1",sampled_at:1000,nonce:"n1"}; const base:any={kind:life?"canary-lifecycle":"canary-tick",source:"src",service:"svc",application:"app",event_id:"e",producer_seq:1,occurred_at:1000,scheduled_for:1000,version:"1",key_id:"key",credential_epoch:"1",payload_digest:life?sha256(canonicalJson(p)):sha256(JSON.stringify(["canary-tick",1,1000,1000,"1"])),monitor_rearm_tuple_digest:"a".repeat(64)}; if(life)base.payload=p; const tuple=[base.kind,base.source,base.service,base.application,base.event_id,base.producer_seq,base.occurred_at,base.scheduled_for,base.version,base.key_id,base.credential_epoch,base.payload_digest,base.monitor_rearm_tuple_digest]; if(life)tuple.push(canonicalJson(p)); base.signature=createHmac("sha256",secret).update(JSON.stringify(tuple)).digest("hex"); return {...base,signature:base.signature}; }
describe("producer envelope authentication",()=>{
 it("accepts canonical tick and lifecycle HMAC vectors",()=>{for(const x of [envelope(),envelope(true)]){expect(parseEnvelope(x)).toEqual(x);expect(authenticateEnvelope(x,registration,secret)).toBe(true);}});
 it("rejects mutations, scope mismatch, replay shape, and unsafe values",()=>{const x=envelope(); for(const field of ["source","service","application","event_id","key_id","credential_epoch","monitor_rearm_tuple_digest"]){const y={...x,[field]:field==="monitor_rearm_tuple_digest"?"b".repeat(64):"changed"};expect(authenticateEnvelope(y,registration,secret)).toBe(false);} expect(()=>parseEnvelope({...x,producer_seq:Number.MAX_SAFE_INTEGER+1})).toThrow(); expect(()=>parseEnvelope({...x,extra:true})).toThrow(); const cyc:any={};cyc.self=cyc;expect(()=>canonicalJson(cyc)).toThrow();});
 it("parses cursor authority and rejects extra or regressing fields",()=>{const c:any={source:"src",service:"svc",application:"app",keyId:"key",credentialEpoch:"1",lastSequence:1,lastEnvelopeDigest:"a".repeat(64),lastOccurredAt:100,lastScheduledFor:100,firstAcceptedAt:100,lastAcceptedAt:200,expectedAt:60100,quarantined:false,lifecycle:["src",1,"tr","healthy",100,"v1"],lastLifecycleNonce:"n1",sourceHealth:"healthy",sourceReason:"ok"}; expect(parseSourceCursor(c)).toEqual(c); const lifecycleReg={...registration,allowedKinds:["canary-lifecycle"],intervalMs:60000,authoritySourceId:"do-authority"}; const authorityCursor={...c,lifecycle:["do-authority",1,"tr","healthy",100,"v1"]}; expect(parseSourceCursor(authorityCursor,lifecycleReg)).toEqual(authorityCursor); expect(()=>parseSourceCursor({...authorityCursor,lifecycle:["wrong-do",1,"tr","healthy",100,"v1"]},lifecycleReg)).toThrow(); expect(()=>parseSourceCursor({...authorityCursor,expectedAt:60101},lifecycleReg)).toThrow(); expect(()=>parseSourceCursor({...authorityCursor,lastScheduledFor:Number.MAX_SAFE_INTEGER,expectedAt:null},lifecycleReg)).toThrow(); const transitionReg={...registration,allowedKinds:["ATTEMPT_RESERVED"],intervalMs:null,authoritySourceId:null}; const transitionCursor={...c,lifecycle:null,lastLifecycleNonce:null,sourceHealth:"unknown",expectedAt:null}; expect(parseSourceCursor(transitionCursor,transitionReg)).toEqual(transitionCursor); expect(()=>parseSourceCursor({...transitionCursor,expectedAt:1},transitionReg)).toThrow(); const stale={...c,lifecycle:null,lastLifecycleNonce:null,sourceHealth:"unknown"}; expect(parseSourceCursor(stale, lifecycleReg)).toEqual(stale); expect(()=>parseSourceCursor(authorityCursor, registration)).toThrow(); expect(()=>parseSourceCursor({...c,lastLifecycleNonce:"nonce-without-tuple"}, lifecycleReg)).toThrow(); expect(()=>parseSourceCursor({...c,extra:true})).toThrow(); expect(()=>parseSourceCursor({...c,firstAcceptedAt:201})).toThrow(); });
 it("requires enabled registration, allowed kind, and a 32-byte secret",()=>{const x=envelope();expect(authenticateEnvelope(x,{...registration,enabled:false},secret)).toBe(false);expect(authenticateEnvelope(x,{...registration,allowedKinds:["canary-lifecycle"]},secret)).toBe(false);expect(authenticateEnvelope(x,registration,new Uint8Array(31))).toBe(false);});
});
