import { describe, expect, it } from "vitest";
import { DynamoDbStateStore, MemoryStateStore, StateBackendError } from "../src/state";
class FakeClient { calls: unknown[] = []; response: any = {}; async send(command: any) { this.calls.push(command.input); if (this.response instanceof Error) throw this.response; return this.response; } }
describe("MemoryStateStore", () => {
  it("commits atomically, versions with CAS, and clones values", async () => { const s = new MemoryStateStore(); expect(await s.transact([{ key:"a", expectedVersion:null, value:{nested:[1]} },{key:"b",expectedVersion:null,value:2}])).toBe("committed"); const a=await s.get<{nested:number[]}>("a"); a!.value.nested.push(9); expect((await s.get("a"))!.value).toEqual({nested:[1]}); expect(await s.transact([{key:"a",expectedVersion:1,value:3},{key:"b",expectedVersion:99,value:4}])).toBe("conflict"); expect(await s.get("a")).toMatchObject({version:1,value:{nested:[1]}}); });
  it("serializes concurrent CAS and paginates with opaque cursor", async () => { const s=new MemoryStateStore(); const results=await Promise.all(Array.from({length:100},()=>s.transact([{key:"same",expectedVersion:null,value:1}]))); expect(results.filter((x)=>x==="committed")).toHaveLength(1); expect(results.filter((x)=>x==="conflict")).toHaveLength(99); await Promise.all(Array.from({length:100},(_,i)=>s.transact([{key:`p:${String(i).padStart(3,"0")}`,expectedVersion:null,value:i}]))); expect((await s.scan("p:")).items).toHaveLength(100); await s.transact([{key:"p:100",expectedVersion:null,value:100}]); const page=await s.scan("p:"); expect(page.items).toHaveLength(100); expect(page.nextCursor).toBeTruthy(); expect((await s.scan("p:",page.nextCursor!)).items).toEqual([{key:"p:100",version:1,value:100}]); await expect(s.scan("")).rejects.toThrow(TypeError); await expect(s.scan("bad\u0000")).rejects.toThrow(TypeError); await expect(s.scan("q:", "not-a-cursor")).rejects.toThrow(TypeError); });
  it("rejects invalid versions, duplicates, and oversized values before mutation", async () => { const s=new MemoryStateStore(); await expect(s.transact([{key:"x",expectedVersion:0,value:1}])).rejects.toThrow(TypeError); await expect(s.transact([{key:"x",expectedVersion:null,value:1},{key:"x",expectedVersion:null,value:2}])).rejects.toThrow(TypeError); await expect(s.transact([{key:"x",expectedVersion:null,value:"x".repeat(400*1024)}])).rejects.toThrow(RangeError); expect(await s.get("x")).toBeNull(); });
});
describe("DynamoDbStateStore", () => {
  it("uses consistent reads and conditional transactions", async () => { const client=new FakeClient(); client.response={Item:{PK:{S:"ns"},SK:{S:"a"},version:{N:"2"},value:{S:'{"ok":true}'}}}; const s=new DynamoDbStateStore({client:client as any,tableName:"state",namespace:"ns"}); expect(await s.get("a")).toEqual({key:"a",version:2,value:{ok:true}}); expect((client.calls[0] as any).ConsistentRead).toBe(true); client.response={}; expect(await s.transact([{key:"a",expectedVersion:2,value:{ok:false}}])).toBe("committed"); expect((client.calls[1] as any).TransactItems[0].Put.ConditionExpression).toContain("#version = :expected"); });
  it("returns conflict only for conditional cancellation and types ambiguous failures", async () => { const client=new FakeClient(); const s=new DynamoDbStateStore({client:client as any,tableName:"state",namespace:"ns"}); client.response=Object.assign(new Error("race"),{name:"TransactionCanceledException",CancellationReasons:[{Code:"ConditionalCheckFailed"}]}); expect(await s.transact([{key:"a",expectedVersion:null,value:1}])).toBe("conflict"); client.response=new Error("timeout"); await expect(s.transact([{key:"a",expectedVersion:null,value:1}])).rejects.toBeInstanceOf(StateBackendError); });
  it("types ambiguous get and scan failures", async () => { const client=new FakeClient(); const s=new DynamoDbStateStore({client:client as any,tableName:"state",namespace:"ns"}); client.response=new Error("read timeout"); await expect(s.get("a")).rejects.toBeInstanceOf(StateBackendError); await expect(s.scan("p:")).rejects.toBeInstanceOf(StateBackendError); });
});
