import type { AckVerifier, TickConfig } from "./config";
export const TICK_DEADLINE_MS = 60_000;
const stateKey = "state", text = new TextEncoder();
const ef = ["event_id","producer_seq","payload_digest","source","service","application","key_id","credential_epoch","monitor_rearm_tuple_digest","occurred_at"] as const;
const af = ["ack_version","event_id","producer_seq","payload_digest","source","service","application","key_id","credential_epoch","monitor_rearm_tuple_digest","ingest_commit_id","committed_at","signer_key_id","signer_epoch"] as const;
const rf = ["recovery_version","event_id","producer_seq","payload_digest","source","service","application","key_id","credential_epoch","original_monitor_rearm_tuple_digest","ingest_commit_id","original_ack_digest","revocation_record_digest","signer_rotation_manifest_digest","signer_manifest_generation","signer_manifest_witness_root_digest","current_monitor_rearm_tuple_digest","recovery_signer_key_id","recovery_signer_epoch","issued_at"] as const;
export interface TickEnvelope { event_id:string; producer_seq:number; payload_digest:string; source:string; service:string; application:string; key_id:string; credential_epoch:string; monitor_rearm_tuple_digest:string; occurred_at:number; signature:string }
export interface AckToken { ack_version:string; event_id:string; producer_seq:number; payload_digest:string; source:string; service:string; application:string; key_id:string; credential_epoch:string; monitor_rearm_tuple_digest:string; ingest_commit_id:string; committed_at:number; signer_key_id:string; signer_epoch:string; signature:string }
export interface AckRecovery { recovery_version:string; event_id:string; producer_seq:number; payload_digest:string; source:string; service:string; application:string; key_id:string; credential_epoch:string; original_monitor_rearm_tuple_digest:string; ingest_commit_id:string; original_ack_digest:string; revocation_record_digest:string; signer_rotation_manifest_digest:string; signer_manifest_generation:number; signer_manifest_witness_root_digest:string; current_monitor_rearm_tuple_digest:string; recovery_signer_key_id:string; recovery_signer_epoch:string; issued_at:number; signature:string }
type Head={envelope:TickEnvelope;enqueuedAt:number}; type State={seq:number;head?:Head;terminal?:"ACKED"|"TIMED_OUT"|"CONFIG_UNAVAILABLE"};
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const str=(v:unknown)=>typeof v==="string"&&v.length>0;
const hex=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
const pos=(v:unknown)=>typeof v==="number"&&Number.isSafeInteger(v)&&v>0;
const time=(v:unknown)=>typeof v==="number"&&Number.isSafeInteger(v)&&v>=0;
const canon=(v:object, keys:readonly string[])=>JSON.stringify(keys.map(k=>(v as Record<string,unknown>)[k]));
function strict(v:unknown, keys:readonly string[], c:Record<string,(x:unknown)=>boolean>):boolean{return obj(v)&&Object.keys(v).length===keys.length+1&&Object.keys(v).every(k=>k==="signature"||keys.includes(k))&&typeof v.signature==="string"&&keys.every(k=>c[k]!(v[k]));}
const ackChecks={ack_version:(v:unknown)=>v==="1",event_id:str,producer_seq:pos,payload_digest:hex,source:str,service:str,application:str,key_id:str,credential_epoch:str,monitor_rearm_tuple_digest:hex,ingest_commit_id:str,committed_at:time,signer_key_id:str,signer_epoch:str};
const recoveryChecks={recovery_version:(v:unknown)=>v==="1",event_id:str,producer_seq:pos,payload_digest:hex,source:str,service:str,application:str,key_id:str,credential_epoch:str,original_monitor_rearm_tuple_digest:hex,ingest_commit_id:str,original_ack_digest:hex,revocation_record_digest:hex,signer_rotation_manifest_digest:hex,signer_manifest_generation:pos,signer_manifest_witness_root_digest:hex,current_monitor_rearm_tuple_digest:hex,recovery_signer_key_id:str,recovery_signer_epoch:str,issued_at:time};
async function sha(v:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",text.encode(v)))].map(n=>n.toString(16).padStart(2,"0")).join("");}
async function mac(v:string,k:string){const key=await crypto.subtle.importKey("raw",text.encode(k),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return [...new Uint8Array(await crypto.subtle.sign("HMAC",key,text.encode(v)))].map(n=>n.toString(16).padStart(2,"0")).join("");}
export async function validAck(ack:AckToken, head:Head, verifier:AckVerifier|undefined, now:number){const e=head.envelope;if(!verifier||!strict(ack,af,ackChecks)||ack.event_id!==e.event_id||ack.producer_seq!==e.producer_seq||ack.payload_digest!==e.payload_digest||ack.source!==e.source||ack.service!==e.service||ack.application!==e.application||ack.key_id!==e.key_id||ack.credential_epoch!==e.credential_epoch||ack.monitor_rearm_tuple_digest!==e.monitor_rearm_tuple_digest||ack.committed_at<head.enqueuedAt||now>=head.enqueuedAt+TICK_DEADLINE_MS)return"invalid" as const;return verifier.verify(canon(ack,af),ack.signature,ack.signer_key_id,ack.signer_epoch);}
export async function validRecovery(r:AckRecovery,head:Head,a:AckToken,v:AckVerifier|undefined,now:number){const e=head.envelope;if(!v||!strict(r,rf,recoveryChecks)||r.event_id!==e.event_id||r.producer_seq!==e.producer_seq||r.payload_digest!==e.payload_digest||r.source!==e.source||r.service!==e.service||r.application!==e.application||r.key_id!==e.key_id||r.credential_epoch!==e.credential_epoch||r.original_monitor_rearm_tuple_digest!==e.monitor_rearm_tuple_digest||r.current_monitor_rearm_tuple_digest!==e.monitor_rearm_tuple_digest||r.ingest_commit_id!==a.ingest_commit_id||r.original_ack_digest!==await sha(JSON.stringify([...JSON.parse(canon(a,af)),a.signature]))||now>=head.enqueuedAt+TICK_DEADLINE_MS)return false;return(await v.verify(canon(r,rf),r.signature,r.recovery_signer_key_id,r.recovery_signer_epoch))==="valid";}
const same=(s:State|undefined,h:Head)=>s?.head?.envelope.event_id===h.envelope.event_id&&s.head.envelope.producer_seq===h.envelope.producer_seq&&s.head.enqueuedAt===h.enqueuedAt;
export class CanaryTickOutbox { constructor(private readonly state:DurableObjectState){} async enqueueAndDrain(c:TickConfig|null,n:number,b=false){return this.state.blockConcurrencyWhile(()=>this.run(c,n,b));}
private async run(c:TickConfig|null,n:number,b:boolean):Promise<string>{let s=(await this.state.storage.get<State>(stateKey))??{seq:0};if(!s.head){if(!c){s.terminal="CONFIG_UNAVAILABLE";await this.state.storage.put(stateKey,s);return"tick config unavailable";}const seq=s.seq+1,kind=b?"CANARY_CONFIG_INVALID":"canary-tick",u={event_id:`${kind}-${seq}`,producer_seq:seq,payload_digest:await sha(`${kind}:${seq}:${n}`),source:c.source,service:c.service,application:c.application,key_id:c.keyId,credential_epoch:c.credentialEpoch,monitor_rearm_tuple_digest:c.monitorRearmTupleDigest,occurred_at:n};s={seq,head:{envelope:{...u,signature:await mac(canon(u,ef),c.envelopeHmacKey)},enqueuedAt:n}};await this.state.storage.transaction(async t=>{await t.put(stateKey,s);await t.setAlarm(n+TICK_DEADLINE_MS);});}if(!c)return"tick head held: config unavailable";const h=s.head!,deadline=h.enqueuedAt+TICK_DEADLINE_MS;if(n>=deadline)return this.terminal(h,"TIMED_OUT");try{const r=await fetch(c.ingestUrl,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(h.envelope),signal:AbortSignal.timeout(Math.max(1,deadline-n))});const body=await r.text();let candidate:unknown=null;try{candidate=r.ok?JSON.parse(body):null;}catch{}if(!r.ok||!same(await this.state.storage.get<State>(stateKey),h)||await validAck(candidate as AckToken,h,c.ackVerifier,Date.now())!=="valid")return"tick head pending: invalid ACK";return this.terminal(h,"ACKED");}catch{return"tick head pending: transmit failed";}}
private async terminal(h:Head,x:State["terminal"]){let won=false;await this.state.storage.transaction(async t=>{const s=await t.get<State>(stateKey);if(!same(s,h))return;s!.head=undefined;s!.terminal=x;await t.put(stateKey,s!);await t.deleteAlarm();won=true;});return won?`tick terminal: ${x}`:"tick head changed";}
async alarm(){await this.state.blockConcurrencyWhile(async()=>{const s=await this.state.storage.get<State>(stateKey);if(!s?.head)return;const d=s.head.enqueuedAt+TICK_DEADLINE_MS;if(Date.now()<d){await this.state.storage.setAlarm(d);return;}await this.terminal(s.head,"TIMED_OUT");});}}
