#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."&&pwd -P)"; H="$ROOT/bin/direct-rotate-production.sh"; W="$ROOT/tests/direct-mock-wrangler.sh"; C="$ROOT/tests/direct-mock-curl.sh"; V="$ROOT/tests/direct-mock-verifier.sh"; pass=0; fail=0
ok(){ pass=$((pass+1));printf 'ok - %s\n' "$1";}; bad(){ fail=$((fail+1));printf 'not ok - %s\n' "$1" >&2;}
new(){ D="$(mktemp -d /private/tmp/corelink-direct-hardening.XXXXXX)";mkdir -m 700 "$D/oob" "$D/repo";git -C "$D/repo" init -q;git -C "$D/repo" config user.email t@x;git -C "$D/repo" config user.name t;mkdir -p "$D/repo/deploy/cloudflare" "$D/repo/deploy/cloudflare-fabricd";printf '%s\n' 'registry.example/spawn@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' >"$D/repo/deploy/cloudflare/wrangler.jsonc";printf '%s\n' 'registry.example/fabric@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' >"$D/repo/deploy/cloudflare-fabricd/wrangler.jsonc";git -C "$D/repo" add .&&git -C "$D/repo" commit -qm b;Q="$(git -C "$D/repo" rev-parse HEAD)";for x in fleet-busy-read-key corelink-canary-tenant-pat old;do printf '%s\n' sentinel-$x>"$D/oob/$x";chmod 600 "$D/oob/$x";done;:>"$D/log";}
run(){ DIRECT_MOCK_LOG="$D/log" DIRECT_MOCK_SPAWN_COUNTER="$D/spawn-counter" DIRECT_MOCK_FAIL="${1:-}" "$H" --mode mock --mock-wrangler "$W" --curl-bin "$C" --verify-bin "$V" --integration-root "$D/repo" --expected-commit "$Q" --spawn-version v-pin --fabricd-version v-pin --spawn-app-id spawn --fabricd-app-id fabric --canary-image registry.example/spawn@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --oob-dir "$D/oob" --fleet-key-file "$D/oob/fleet-busy-read-key" --canary-pat-file "$D/oob/corelink-canary-tenant-pat" --old-token-file "$D/oob/old" --evidence-dir "$D/evidence";}
chmod +x "$H" "$W" "$C" "$V" "$ROOT/bin/verify-close-attestation.mjs"
if PATH=/nope /bin/bash "$H" >/dev/null;then ok plan;else bad plan;fi
new;if run&&grep -q complete_final_frozen "$D/evidence/events.log"&&! grep -E 'sentinel-(fleet|corelink|old)' "$D/evidence/events.log";then ok success_sanitized;else bad success_sanitized;fi;rm -rf "$D"
new;if run release_fabricd >/dev/null 2>&1;then bad release_failure;elif grep -q 'release_transition=marked' "$D/evidence/events.log"&&grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok release_failure_refreezes;else bad release_failure_refreezes;fi;rm -rf "$D"
if bash -n "$H"&&shellcheck "$H" "$W" "$C" "$V";then ok syntax_shellcheck;else bad syntax_shellcheck;fi
[ "$fail" -eq 0 ]||exit 1;printf '%s tests passed\n' "$pass"
