#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."&&pwd -P)"; H="$ROOT/bin/direct-rotate-production.sh"; W="$ROOT/tests/direct-mock-wrangler.sh"; C="$ROOT/tests/direct-mock-curl.sh"; V="$ROOT/tests/direct-mock-verifier.sh"; S="$ROOT/tests/direct-dispatch-spawn-wrangler.sh"; F="$ROOT/tests/direct-dispatch-fabricd-wrangler.sh"; B="$ROOT/tests/direct-dispatch-wrangler-wrong-version.sh"; pass=0; fail=0
ok(){ pass=$((pass+1));printf 'ok - %s\n' "$1";}; bad(){ fail=$((fail+1));printf 'not ok - %s\n' "$1" >&2;}
new(){ D="$(mktemp -d /private/tmp/corelink-direct-hardening.XXXXXX)";mkdir -m 700 "$D/oob" "$D/repo";git -C "$D/repo" init -q;git -C "$D/repo" config user.email t@x;git -C "$D/repo" config user.name t;mkdir -p "$D/repo/deploy/cloudflare/node_modules/.bin" "$D/repo/deploy/cloudflare-fabricd/node_modules/.bin";printf '%s\n' 'registry.example/spawn@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' >"$D/repo/deploy/cloudflare/wrangler.jsonc";printf '%s\n' 'registry.example/fabric@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' >"$D/repo/deploy/cloudflare-fabricd/wrangler.jsonc";cp "$S" "$D/repo/deploy/cloudflare/node_modules/.bin/wrangler";cp "$F" "$D/repo/deploy/cloudflare-fabricd/node_modules/.bin/wrangler";chmod 700 "$D/repo/deploy/cloudflare/node_modules/.bin/wrangler" "$D/repo/deploy/cloudflare-fabricd/node_modules/.bin/wrangler";git -C "$D/repo" add .&&git -C "$D/repo" commit -qm b;Q="$(git -C "$D/repo" rev-parse HEAD)";for x in fleet-busy-read-key corelink-canary-tenant-pat old;do printf '%s\n' sentinel-$x>"$D/oob/$x";chmod 600 "$D/oob/$x";done;:>"$D/log";:>"$D/dispatch.log";}
run(){ DIRECT_MOCK_LOG="$D/log" DIRECT_MOCK_WRANGLER="$W" DIRECT_DISPATCH_LOG="$D/dispatch.log" DIRECT_MOCK_WAKE_FILE="${DIRECT_MOCK_WAKE_FILE:-}" DIRECT_MOCK_SPAWN_COUNTER="$D/spawn-counter" DIRECT_MOCK_FLEET_COUNTER="$D/fleet-counter" DIRECT_MOCK_KEY_COUNTER="$D/key-counter" DIRECT_MOCK_INSTANCE_COUNTER="$D/instance-counter" DIRECT_MOCK_DISCOVERY_COUNTER="$D/discovery-counter" DIRECT_MOCK_DISCOVERY_MODE="${DIRECT_MOCK_DISCOVERY_MODE:-ready}" DIRECT_MOCK_DISCOVERY_AFTER="${DIRECT_MOCK_DISCOVERY_AFTER:-2}" DIRECT_MOCK_INSTANCE_DELAY="${DIRECT_MOCK_INSTANCE_DELAY:-}" DIRECT_MOCK_INSTANCE_PID_FILE="${DIRECT_MOCK_INSTANCE_PID_FILE:-}" DIRECT_MOCK_CONVERGENCE_MODE="${DIRECT_MOCK_CONVERGENCE_MODE:-ready}" DIRECT_MOCK_CONVERGENCE_AFTER="${DIRECT_MOCK_CONVERGENCE_AFTER:-2}" DIRECT_MOCK_INSTANCE_DIGEST="${DIRECT_MOCK_INSTANCE_DIGEST:-present}" DIRECT_MOCK_INFO_MODE="${DIRECT_MOCK_INFO_MODE:-exact}" DIRECT_MOCK_SECRET_LIST="${DIRECT_MOCK_SECRET_LIST:-present}" DIRECT_MOCK_FAIL="${1:-}" DIRECT_MOCK_DELETE_MODE="${DIRECT_MOCK_DELETE_MODE:-}" DIRECT_MOCK_DELETE_DELAY="${DIRECT_MOCK_DELETE_DELAY:-}" DIRECT_MOCK_MUTATE_FILE="${DIRECT_MOCK_MUTATE_FILE:-}" "$H" --mode mock --mock-wrangler "$W" --curl-bin "$C" --verify-bin "$V" --stability-secs 0 --delete-timeout-seconds "${DIRECT_DELETE_TIMEOUT:-30}" --fabricd-convergence-timeout-seconds "${DIRECT_CONVERGENCE_TIMEOUT:-5}" --fabricd-convergence-interval-seconds "${DIRECT_CONVERGENCE_INTERVAL:-1}" --fabricd-command-timeout-seconds "${DIRECT_COMMAND_TIMEOUT:-2}" --attempt "${DIRECT_ATTEMPT:-primary}" --integration-root "$D/repo" --expected-commit "$Q" --spawn-version v-pin --fabricd-version v-pin --spawn-app-id 11111111-1111-1111-1111-111111111111 --fabricd-app-id 22222222-2222-2222-2222-222222222222 --canary-image registry.example/spawn@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --oob-dir "$D/oob" --fleet-key-file "$D/oob/fleet-busy-read-key" --canary-pat-file "$D/oob/corelink-canary-tenant-pat" --old-token-file "$D/oob/old" --evidence-dir "$D/evidence" ${DIRECT_BOOTSTRAP_SPLIT_AUTH:+--bootstrap-split-auth};}
assert_mock_wake_transition(){
  local log="$D/wake-mock.log" wake="$D/wake-mock"
  DIRECT_MOCK_LOG="$log" DIRECT_MOCK_WAKE_FILE="$wake" "$W" containers instances fixture --json >"$D/wake-stopped"
  grep -q '"state":"stopped"' "$D/wake-stopped"
  : > "$wake"
  DIRECT_MOCK_LOG="$log" DIRECT_MOCK_WAKE_FILE="$wake" "$W" containers instances fixture --json >"$D/wake-running"
  grep -q '"state":"running"' "$D/wake-running"
}
chmod +x "$H" "$W" "$C" "$V" "$ROOT/bin/verify-close-attestation.mjs"
if PATH=/nope /bin/bash "$H" >/dev/null;then ok plan;else bad plan;fi
new;if run&&grep -q complete_final_frozen "$D/evidence/events.log"&&grep -q 'control_probes_under_freeze=spawn:503/401 exec:400/401 lifecycle:404/401' "$D/evidence/events.log"&&grep -q 'fleet_header=x-corelink-internal-auth' "$D/log"&&[ "$(grep -c 'fleet_header=x-corelink-internal-auth' "$D/log")" = 2 ]&&[ "$(grep -c 'secret_put_valid_single_line' "$D/log")" = 7 ]&&grep -q 'fleet_post_canary=busy:0 unverifiable:0' "$D/evidence/events.log"&&grep -q 'attestation_key=changed_from:0123456789abcdef_to:fedcba9876543210_single_active' "$D/evidence/events.log"&&grep -q 'fabricd_convergence=ready .*running:1 failed:0 .*source:instances .*health:200_ok' "$D/evidence/events.log"&&grep -Fq 'wrangler secret list --name corelink-spawn-worker --format json' "$D/log"&&grep -Fq 'wrangler secret list --name corelink-fabricd --format json' "$D/log"&&grep -Fq "dispatch=spawn cwd=$D/repo/deploy/cloudflare args=deploy --config $D/repo/deploy/cloudflare/wrangler.jsonc --keep-vars --var FABRIC_ADMISSION_PAUSED:1" "$D/dispatch.log"&&grep -Fq "dispatch=fabricd cwd=$D/repo/deploy/cloudflare-fabricd args=deploy --config $D/repo/deploy/cloudflare-fabricd/wrangler.jsonc --keep-vars --var FABRIC_ADMISSION_PAUSED:1 --containers-rollout=immediate" "$D/dispatch.log"&&grep -Fq "dispatch=spawn cwd=$D/repo/deploy/cloudflare args=secret put CLOUDFLARE_SPAWN_AUTH_TOKEN --config $D/repo/deploy/cloudflare/wrangler.jsonc" "$D/dispatch.log"&&grep -Fq "dispatch=fabricd cwd=$D/repo/deploy/cloudflare-fabricd args=secret put FABRIC_SIGNING_KEY" "$D/dispatch.log"&&[ "$(grep -n "dispatch=spawn cwd=$D/repo/deploy/cloudflare args=secret put CLOUDFLARE_SPAWN_AUTH_TOKEN" "$D/dispatch.log"|head -1|cut -d: -f1)" -lt "$(grep -n "dispatch=spawn cwd=$D/repo/deploy/cloudflare args=secret put CLOUDFLARE_EXEC_AUTH_TOKEN" "$D/dispatch.log"|head -1|cut -d: -f1)" ]&&[ "$(grep -n "dispatch=spawn cwd=$D/repo/deploy/cloudflare args=secret put CLOUDFLARE_EXEC_AUTH_TOKEN" "$D/dispatch.log"|head -1|cut -d: -f1)" -lt "$(grep -n "dispatch=spawn cwd=$D/repo/deploy/cloudflare args=secret put CLOUDFLARE_LIFECYCLE_AUTH_TOKEN" "$D/dispatch.log"|head -1|cut -d: -f1)" ]&&[ "$(grep -n "dispatch=fabricd cwd=$D/repo/deploy/cloudflare-fabricd args=secret put FABRIC_SIGNING_KEY" "$D/dispatch.log"|head -1|cut -d: -f1)" -lt "$(grep -n "dispatch=fabricd cwd=$D/repo/deploy/cloudflare-fabricd args=secret put CLOUDFLARE_SPAWN_AUTH_TOKEN" "$D/dispatch.log"|head -1|cut -d: -f1)" ]&&[ "$(grep -n '^fabricd_delete$' "$D/log"|cut -d: -f1)" -lt "$(grep -n '^fabricd_absence_confirmed$' "$D/log"|cut -d: -f1)" ]&&[ "$(grep -n '^fabricd_absence_confirmed$' "$D/log"|cut -d: -f1)" -lt "$(grep -n '^fabricd_recreate$' "$D/log"|cut -d: -f1)" ]&&! grep -E 'sentinel-(fleet|corelink|old)' "$D/evidence/events.log" "$D/log";then ok success_sanitized_post_canary_fleet_key_change_health;else bad success_sanitized_post_canary_fleet_key_change_health;fi;rm -rf "$D"
new;if DIRECT_MOCK_WAKE_FILE="$D/wake" assert_mock_wake_transition&&DIRECT_MOCK_WAKE_FILE="$D/wake" run&&grep -q 'fabricd_health_wake=status:200' "$D/evidence/events.log"&&grep -q complete_final_frozen "$D/evidence/events.log"&&grep -q '^fabricd_instance_state=running$' "$D/log"&&[ "$(grep -n '^fabricd_health_wake_request$' "$D/log"|head -1|cut -d: -f1)" -lt "$(grep -n '^fabricd_instances$' "$D/log"|head -1|cut -d: -f1)" ]&&[ "$(grep -n 'fabricd_health_wake=status:200' "$D/evidence/events.log"|head -1|cut -d: -f1)" -lt "$(grep -n 'fabricd_convergence=ready' "$D/evidence/events.log"|head -1|cut -d: -f1)" ]&&! grep -q '^fabricd_instance_state=stopped$' "$D/log";then ok health_wake_precedes_instance_convergence;else bad health_wake_precedes_instance_convergence;fi;rm -rf "$D"
new;if DIRECT_MOCK_INSTANCE_DIGEST=absent run >/dev/null 2>&1&&grep -q 'fabricd_convergence=ready .*source:config-info .*health:200_ok' "$D/evidence/events.log"&&grep -q complete_final_frozen "$D/evidence/events.log";then ok convergence_digest_absent_uses_exact_config_info;else bad convergence_digest_absent_uses_exact_config_info;fi;rm -rf "$D"
new;if DIRECT_MOCK_SECRET_LIST=missing run >/dev/null 2>"$D/err";then bad empty_bindings_refused;elif grep -q 'missing control bindings for spawn: CLOUDFLARE_SPAWN_AUTH_TOKEN,CLOUDFLARE_EXEC_AUTH_TOKEN,CLOUDFLARE_LIFECYCLE_AUTH_TOKEN' "$D/err";then ok empty_bindings_refused;else bad empty_bindings_refused;fi;rm -rf "$D"
new;if DIRECT_MOCK_SECRET_LIST=partial run >/dev/null 2>"$D/err";then bad partial_bindings_refused;elif grep -q 'missing control bindings for spawn: CLOUDFLARE_EXEC_AUTH_TOKEN,CLOUDFLARE_LIFECYCLE_AUTH_TOKEN' "$D/err";then ok partial_bindings_refused;else bad partial_bindings_refused;fi;rm -rf "$D"
new;if DIRECT_MOCK_SECRET_LIST=partial DIRECT_BOOTSTRAP_SPLIT_AUTH=1 run >/dev/null 2>"$D/err";then bad partial_bindings_bootstrap_marker;elif grep -q 'bootstrap_split_auth=explicit' "$D/evidence/events.log";then ok partial_bindings_bootstrap_marker;else bad partial_bindings_bootstrap_marker;fi;rm -rf "$D"
new;if DIRECT_MOCK_CONVERGENCE_MODE=delayed DIRECT_MOCK_CONVERGENCE_AFTER=3 run >/dev/null 2>&1&&grep -q 'fabricd_convergence=ready poll:3 .*running:1 failed:0' "$D/evidence/events.log";then ok convergence_delayed_succeeds;else bad convergence_delayed_succeeds;fi;rm -rf "$D"
new;if DIRECT_MOCK_DISCOVERY_MODE=delayed DIRECT_MOCK_DISCOVERY_AFTER=3 DIRECT_CONVERGENCE_TIMEOUT=5 run >/dev/null 2>&1&&grep -q 'fabricd_discovery=ready poll:3 ' "$D/evidence/events.log"&&grep -q complete_final_frozen "$D/evidence/events.log"&&[ "$(<"$D/discovery-counter")" = 3 ];then ok discovery_delayed_zero_to_one_succeeds;else bad discovery_delayed_zero_to_one_succeeds;fi;rm -rf "$D"
new;if DIRECT_MOCK_DISCOVERY_MODE=never DIRECT_CONVERGENCE_TIMEOUT=2 DIRECT_CONVERGENCE_INTERVAL=1 run >/dev/null 2>&1;then bad discovery_never_times_out;elif grep -q 'fabricd_discovery=timeout polls:2' "$D/evidence/events.log"&&grep -q 'exit_refreeze=attempted' "$D/evidence/events.log"&&[ "$(<"$D/discovery-counter")" = 2 ];then ok discovery_never_times_out_refreezes;else bad discovery_never_times_out_refreezes;fi;rm -rf "$D"
new;if DIRECT_MOCK_DISCOVERY_MODE=ambiguous run >/dev/null 2>&1;then bad discovery_ambiguous_refused;elif grep -q 'fabricd_discovery=ambiguous poll:1' "$D/evidence/events.log"&&grep -q 'exit_refreeze=attempted' "$D/evidence/events.log"&&[ "$(grep -c 'containers list --json' "$D/log")" = 2 ]&&[ "$(grep -n 'containers list --json' "$D/log"|tail -1|cut -d: -f1)" -gt "$(grep -n '^fabricd_recreate$' "$D/log"|tail -1|cut -d: -f1)" ];then ok discovery_ambiguous_refused;else bad discovery_ambiguous_refused;fi;rm -rf "$D"
new;if DIRECT_MOCK_CONVERGENCE_MODE=never DIRECT_CONVERGENCE_TIMEOUT=2 DIRECT_CONVERGENCE_INTERVAL=1 run >/dev/null 2>&1;then bad convergence_never_times_out;elif grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok convergence_never_times_out_refreezes;else bad convergence_never_times_out_refreezes;fi;rm -rf "$D"
new;if DIRECT_MOCK_CONVERGENCE_MODE=wrong-digest run >/dev/null 2>&1;then bad convergence_wrong_digest_refused;elif grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok convergence_wrong_digest_refused_refreezes;else bad convergence_wrong_digest_refused_refreezes;fi;rm -rf "$D"
new;if DIRECT_MOCK_INFO_MODE=wrong run >/dev/null 2>&1;then bad config_info_wrong_digest_refused;elif ! grep -q '^fabricd_delete$' "$D/log" && ! grep -q 'freeze=spawn_then_fabricd' "$D/evidence/events.log";then ok config_info_wrong_digest_refused_before_mutation;else bad config_info_wrong_digest_refused_before_mutation;fi;rm -rf "$D"
new;if DIRECT_MOCK_CONVERGENCE_MODE=failed run >/dev/null 2>&1;then bad convergence_failed_instance_refused;elif grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok convergence_failed_instance_refused_refreezes;else bad convergence_failed_instance_refused_refreezes;fi;rm -rf "$D"
new;DIRECT_MOCK_INSTANCE_PID_FILE="$D/instance.pid";if DIRECT_MOCK_INSTANCE_DELAY=5 DIRECT_COMMAND_TIMEOUT=1 run >/dev/null 2>&1;then bad convergence_command_timeout;elif [ -s "$D/instance.pid" ]&&pid="$(<"$D/instance.pid")"&&! kill -0 "$pid" 2>/dev/null&&grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok convergence_command_timeout_reaps_and_refreezes;else bad convergence_command_timeout_reaps_and_refreezes;fi;rm -rf "$D"
new;if DIRECT_MOCK_SECRET_LIST=malformed run >/dev/null 2>"$D/err";then bad malformed_bindings_refused;elif grep -q 'secret list preflight failed: spawn' "$D/err";then ok malformed_bindings_refused;else bad malformed_bindings_refused;fi;rm -rf "$D"
new;if DIRECT_MOCK_SECRET_LIST=stderr run >/dev/null 2>"$D/err";then ok secret_list_stderr_isolated;else bad secret_list_stderr_isolated;fi;rm -rf "$D"
new;if DIRECT_MOCK_LOG="$D/log" "$W" secret list --name corelink-spawn-worker --json >"$D/out" 2>"$D/err";then bad incompatible_secret_list_flag_rejected;elif grep -q 'unknown or unsupported secret list format' "$D/err";then ok incompatible_secret_list_flag_rejected;else bad incompatible_secret_list_flag_rejected;fi;rm -rf "$D"
new;rm -f "$D/repo/deploy/cloudflare/node_modules/.bin/wrangler";if run >/dev/null 2>&1;then bad local_wrangler_missing;elif ! grep -q '^wrangler ' "$D/log";then ok local_wrangler_missing_refused_before_mutation;else bad local_wrangler_missing_refused_before_mutation;fi;rm -rf "$D"
new;cp "$B" "$D/repo/deploy/cloudflare/node_modules/.bin/wrangler";chmod 700 "$D/repo/deploy/cloudflare/node_modules/.bin/wrangler";if run >/dev/null 2>&1;then bad local_wrangler_version_mismatch;elif ! grep -q '^wrangler ' "$D/log";then ok local_wrangler_version_mismatch_refused_before_mutation;else bad local_wrangler_version_mismatch_refused_before_mutation;fi;rm -rf "$D"
new;if run release_fabricd >/dev/null 2>&1;then bad release_failure;elif grep -q 'release_transition=marked' "$D/evidence/events.log"&&grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok release_failure_refreezes;else bad release_failure_refreezes;fi;rm -rf "$D"
new;if run fleet_post_busy >/dev/null 2>&1;then bad post_canary_fleet_busy;elif grep -q 'release_transition=marked' "$D/evidence/events.log"&&grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok post_canary_fleet_busy_refreezes;else bad post_canary_fleet_busy_refreezes;fi;rm -rf "$D"
new;if run health_status >/dev/null 2>&1;then bad health_status;elif ! grep -q 'FABRIC_ADMISSION_PAUSED:0' "$D/log";then ok health_status_blocks_release;else bad health_status_blocks_release;fi;rm -rf "$D"
new;if run health_schema >/dev/null 2>&1;then bad health_schema;elif ! grep -q 'FABRIC_ADMISSION_PAUSED:0' "$D/log";then ok health_schema_blocks_release;else bad health_schema_blocks_release;fi;rm -rf "$D"
new;ln -s /private/tmp "$D/evidence";if run >/dev/null 2>&1;then bad evidence_symlink;elif ! grep -q '^wrangler ' "$D/log";then ok evidence_symlink_blocks_before_mutation;else bad evidence_symlink_blocks_before_mutation;fi;rm -rf "$D"
new;if run same_key >/dev/null 2>&1;then bad same_attestation_key;elif grep -q 'exit_refreeze=attempted' "$D/evidence/events.log";then ok same_attestation_key_refreezes;else bad same_attestation_key_refreezes;fi;rm -rf "$D"
new;if DIRECT_DELETE_TIMEOUT=1 DIRECT_MOCK_DELETE_MODE=timeout-absent DIRECT_MOCK_DELETE_DELAY=2 run >/dev/null 2>&1 && grep -q 'fabricd_container_absence_confirmed.*delete_rc:124' "$D/evidence/events.log" && grep -q '^fabricd_recreate$' "$D/log";then ok delete_timeout_absence_confirmed;else bad delete_timeout_absence_confirmed;fi;rm -rf "$D"
new;if DIRECT_DELETE_TIMEOUT=1 DIRECT_MOCK_DELETE_MODE=timeout-unconfirmed DIRECT_MOCK_DELETE_DELAY=2 run >/dev/null 2>&1;then bad delete_timeout_absence_unconfirmed;elif grep -q 'exit_refreeze=attempted' "$D/evidence/events.log" && ! grep -q '^fabricd_recreate$' "$D/log";then ok delete_timeout_absence_unconfirmed_refreezes;else bad delete_timeout_absence_unconfirmed_refreezes;fi;rm -rf "$D"
new;if DIRECT_MOCK_DELETE_MODE=unconfirmed run >/dev/null 2>&1;then bad delete_no_timeout_absence_unconfirmed;elif grep -q 'exit_refreeze=attempted' "$D/evidence/events.log" && ! grep -q '^fabricd_recreate$' "$D/log";then ok delete_no_timeout_absence_unconfirmed_refreezes;else bad delete_no_timeout_absence_unconfirmed_refreezes;fi;rm -rf "$D"
new;for x in primary.fabric-signing-seed.b64 primary.spawn-token.b64 recovery.fabric-signing-seed.b64 recovery.spawn-token.b64;do printf '%s' validsecret > "$D/oob/$x";chmod 600 "$D/oob/$x";done;printf '%s\n' invalid > "$D/oob/recovery.fabric-signing-seed.b64";if DIRECT_ATTEMPT=recovery run >/dev/null 2>&1;then bad recovery_invalid_secret;elif ! grep -q 'secret_put_valid_single_line' "$D/log";then ok recovery_invalid_secret_refused_before_put;else bad recovery_invalid_secret_refused_before_put;fi;rm -rf "$D"
new;if DIRECT_MOCK_MUTATE_FILE="$D/oob/primary.exec-token.b64" run mutate_after_secret >"$D/stdout" 2>"$D/err";then bad secret_mutation_between_puts;elif [ "$(grep -c 'secret_put_valid_single_line' "$D/log")" = 1 ] && grep -q 'secret validation failed immediately before put: CLOUDFLARE_EXEC_AUTH_TOKEN' "$D/err";then ok secret_mutation_between_puts_refused;else bad secret_mutation_between_puts_refused;fi;rm -rf "$D"
if bash -n "$H"&&shellcheck "$H" "$W" "$C" "$V" "$S" "$F" "$B";then ok syntax_shellcheck;else bad syntax_shellcheck;fi
[ "$fail" -eq 0 ]||exit 1;printf '%s tests passed\n' "$pass"
